<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>37b160e7-3309-4c75-9484-eb5271ec1faf</UserSecretsId>
    <PackageId>FootLook.Core</PackageId>
    <Version>1.0.0</Version>
    <Authors>Mfundo Mthembu</Authors>
    <Description>Real-time API observability middleware for ASP.NET Core with capture, privacy masking, reliability telemetry, and operational endpoints.</Description>
    <PackageTags>footlook;observability;aspnetcore;middleware;monitoring;tracing;api</PackageTags>
    <PackageProjectUrl>https://github.com/mfundomt/FootLook--Zero-Interaction-API-Observability</PackageProjectUrl>
    <RepositoryUrl>https://github.com/mfundomt/FootLook--Zero-Interaction-API-Observability</RepositoryUrl>
    <PackageReadmeFile>README.NuGet.md</PackageReadmeFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.NuGet.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
  </ItemGroup>

</Project>
